stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Data_Train.xlsx
    outs:
    - data/raw/Data_Train.csv

  Handle_Nulls:
    cmd: python src/handlingnull.py --config=params.yaml
    deps:
      - src/handlingnull.py
      - data/raw/Data_Train.csv
    outs:
      - data/processed/train_flightprice.csv

  Data_Transformation_01:
    cmd: python src/dataTransfomration01.py --config=params.yaml
    deps:
      - src/dataTransfomration01.py
      - data/processed/train_flightprice.csv
    outs:
      - data/Transformed01/train_flightprice.csv

  Data_Transformation_02:
    cmd: python src/dataTransformation02.py --config=params.yaml
    deps:
      - src/dataTransformation02.py
      - data/Transformed01/train_flightprice.csv
    outs:
      - data/Transformed02/train_flightprice.csv

  Data_Transformation_03:
    cmd: python src/dataTransformation03.py --config=params.yaml
    deps:
      - src/dataTransformation03.py
      - data/Transformed02/train_flightprice.csv
    outs:
      - data/Transformed03/train_flightprice.csv

  Data_Transformation_04:
    cmd: python src/dataTransformation04.py --config=params.yaml
    deps:
      - src/dataTransformation04.py
      - data/Transformed03/train_flightprice.csv
    outs:
      - data/Transformed04/train_flightprice.csv

  Data_Transformation_05:
    cmd: python src/dataTransformation05.py --config=params.yaml
    deps:
      - src/dataTransformation05.py
      - data/Transformed04/train_flightprice.csv
    outs:
      - data/Transformed05/train_flightprice.csv

  Data_Transformation_06:
    cmd: python src/dataTransformation06.py --config=params.yaml
    deps:
      - src/dataTransformation06.py
      - data/Transformed05/train_flightprice.csv
    outs:
      - data/Transformed06/train_flightprice.csv

  Data_Transformation_07:
    cmd: python src/dataTransformation07.py --config=params.yaml
    deps:
      - src/dataTransformation07.py
      - data/Transformed06/train_flightprice.csv
    outs:
      - data/Transformed07/train_flightprice.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/Transformed07/train_flightprice.csv
    outs:
      - data/Transformed08/train_flightprice.csv
      - data/Transformed08/test_flightprice.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/Transformed08/train_flightprice.csv
      - data/Transformed08/test_flightprice.csv
      - src/train_and_evaluate.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio

  log_production_model:
    cmd: python src/log_production_model.py --config=params.yaml
    deps:
      - src/log_production_model.py