stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Data_Train.xlsx
    outs:
    - data/raw/Data_Train.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
      - src/split_data.py
      - data/raw/Data_Train.csv
    outs:
      - data/processed/train_flightprice.csv
      - data/processed/test_flightprice.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
      - data/processed/train_flightprice.csv
      - data/processed/test_flightprice.csv
      - src/train_and_evaluate.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio